package gr.pkcoding.peoplescope.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val md_theme_light_primary = Color(0xFF00796B)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFB2DFDB)
val md_theme_light_onPrimaryContainer = Color(0xFF00251F)
val md_theme_light_secondary = Color(0xFF4A635F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCE8E2)
val md_theme_light_onSecondaryContainer = Color(0xFF06201C)
val md_theme_light_tertiary = Color(0xFF456179)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCCE5FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001E31)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_background = Color(0xFFF5FAFA)
val md_theme_light_surface = Color(0xFFF5FAFA)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E2)
val md_theme_light_onSurface = Color(0xFF161D1C)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4947)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFF4DB6AC)
val md_theme_dark_onPrimary = Color(0xFF003830)
val md_theme_dark_primaryContainer = Color(0xFF005048)
val md_theme_dark_onPrimaryContainer = Color(0xFFB2DFDB)
val md_theme_dark_secondary = Color(0xFFB0CCC7)
val md_theme_dark_onSecondary = Color(0xFF1C3531)
val md_theme_dark_secondaryContainer = Color(0xFF324B47)
val md_theme_dark_onSecondaryContainer = Color(0xFFCCE8E2)
val md_theme_dark_tertiary = Color(0xFFADCAE6)
val md_theme_dark_onTertiary = Color(0xFF15334A)
val md_theme_dark_tertiaryContainer = Color(0xFF2D4961)
val md_theme_dark_onTertiaryContainer = Color(0xFFCCE5FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_background = Color(0xFF0E1514)
val md_theme_dark_surface = Color(0xFF0E1514)
val md_theme_dark_surfaceVariant = Color(0xFF3F4947)
val md_theme_dark_onSurface = Color(0xFFDEE4E3)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C6)